In [2]:
import numpy as np

#### Creating numpy/n-d array


In [4]:
arr1 = np.array([1,2 ,3 ,4,5])
arr1

array([1, 2, 3, 4, 5])

In [5]:
type(arr1)

numpy.ndarray

In [7]:
arr2 = np.array([[1,2,3], [4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
arr3 = np.zeros((2, 3), dtype=int)
arr3

array([[0, 0, 0],
       [0, 0, 0]])

In [13]:
arr4 = np.ones((3, 3), dtype=int)
arr4

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [17]:
arr4.dtype

dtype('int64')

In [23]:
arr5 = np.identity(4)
arr5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
arr6 = np.arange(5, 16, 2)
arr6

array([ 5,  7,  9, 11, 13, 15])

In [27]:
arr7= np.linspace(10, 20, 10)
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [28]:
arr8= arr7.copy() # hard copy
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [30]:
arr8[0] = 30 #arr7 will not change
arr8

array([30.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

#### Properties and attributes

In [32]:
arr1.shape

(5,)

In [34]:
arr2.shape

(2, 3)

In [41]:
arr9 = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
arr9

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [42]:
arr9.shape

(2, 2, 2)

In [43]:
arr9.ndim

3

In [44]:
arr2.ndim

2

In [45]:
arr1.ndim

1

In [46]:
arr1.size

5

In [47]:
arr2.size

6

In [49]:
arr9.itemsize

8

In [50]:
arr9.dtype

dtype('int64')

In [54]:
arr9 = arr9.astype('float')

In [55]:
arr9.dtype

dtype('float64')

#### Numpy array vs python list

In [62]:
lista = range(100000)
arr11 = np.arange(100000)

In [63]:
import sys
print(sys.getsizeof(87)*len(lista))
print(arr11.itemsize*arr11.size)


2800000
800000


In [76]:
import time

x = list(range(10000000))
y = list(range(10000000, 20000000))

start_time = time.time()
c = [x+y for x, y in zip(x, y)]

print(f'total time: {time.time()-start_time}')

total time: 0.19887590408325195


In [77]:
x = np.arange(10000000)
y = np.arange(10000000, 20000000)

start_time = time.time()
c = x+y

print(f'total time: {time.time()-start_time}')

total time: 0.056566715240478516
